CREATE TABLE PROFILE (
    USERNAME VARCHAR(16) PRIMARY KEY,
    PASSWORD CHAR(128) NOT NULL,
    NAME VARCHAR(80),
    IS_ADMIN BOOLEAN,
    STATUS ENUM('NEW', 'ACTIVE', 'INACTIVE'),
    CREATED_AT TIMESTAMP
)

CREATE TABLE POST (
    POST_ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATED_BY VARCHAR(16),
    CONTENT CHAR(128),
    FILE CHAR(128),
    STATUS ENUM('PENDING', 'ACTIVE', 'INACTIVE'),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (CREATED_BY) REFERENCES PROFILE(USERNAME)
)